services:
  iris-nginx:
    image: nginx:1.27-alpine
    container_name: iris-nginx
    ports:
      - "8081:80"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
    networks:
      - iris-net

networks:
  iris-net:
    name: iris-net

